### ISSUE TITLE
huginn latest version

### ISSUE THREAD

**Issue by emilburzo** [unixfox/periodic-build-with-github-actions#7]
First off, thanks for providing `quay.io/unixfox/huginn-single-process`, it's really cool to be able to use huginn on a raspberry!

I just noticed huginn had a new release but no new docker image. 

From [your comment](https://github.com/huginn/huginn/issues/2648#issuecomment-1010069873) I understood that it should be kept in sync automatically.

Did that change?

**Comment by unixfox** [comment]
Unfortunately the build process broke a while ago and I haven't had the time to fix it: https://github.com/unixfox/periodic-build-with-github-actions/actions/workflows/docker-build-huginn.yml

It seems like it's related to a dependency that is not fully compatible with ARM.

I'll close your issue because I have already an issue for tracking this problem: https://github.com/unixfox/periodic-build-with-github-actions/issues/3
